### PR TITLE
Support for yotta configuration

### PR DESCRIPTION
**Pull request by artokin**
Add basic nannostack configuration to config.json. No need to link
mbed-mesh-api anymore to make config changes.

@SeppoTakalo , please review

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
+1
Looks clean to me

**Comment by artokin** [comment]
@mikter, @SeppoTakalo woudl you plese review. Original yotta configuration updated.

**Comment by artokin** [comment]
@jpellikk-arm

**Comment by artokin** [comment]
@hasnainvirk

**Pull request merged**
