### PR TITLE
Adding config.json to remove LWIP dependency.

### PR DESCRIPTION
**Pull request by yogpan01**

### CODE REVIEW

**Comment by yogpan01** [comment]
@SeppoTakalo Please review.

**Comment by yogpan01** [comment]
There is now fixed test dependency on mbed-client, this 6LoWPAN example should work fine.

**Comment by SeppoTakalo** [comment]
+1

**Comment by SeppoTakalo** [comment]
Deleting this, as it is already done in Techcon-release branch.

**Pull request closed without merging**
